name: cl_server_dart_client
description: Dart client library for CL Server microservices (Auth, Store, Compute).
version: 0.1.0
repository: https://github.com/cloudonlanapps/cl_server_dart_client.git

publish_to: none 

environment:
  sdk: ^3.10.1

dependencies:
  cl_basic_types:
    path: ../../apps/ui_flutter/cl_basic_types
  collection: ^1.19.1
  encrypt: ^5.0.0
  http: ^1.1.0
  http_parser: ^4.1.2
  image: ^4.0.0
  meta: ^1.9.0
  mime: ^2.0.0
  mqtt_client: ^10.0.0
  socket_io_client: ^3.1.2
  solidart: ^1.0.0
  uuid: ^4.5.2

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
  typed_data: ^1.4.0
  very_good_analysis: ^10.0.0
